name: "Check documentation"
description: "Verifies that the documentation fullfils the specification"
inputs:
  token:
    description: 'The GitHub token'
    required: false
    default: ${{ github.token }}
  path:
    description: "The directory with the documentation"
    required: true
  artifact:
    description: "The name of the output artifact"
    required: false
    default: "documentation.json"
runs:
  using: "composite"
  steps:
    - name: Download documentation checker
      run: |
        set -eou pipefail
        ASSET_URL="https://github.com/${ORG}/${REPOSITORY}/releases/download/$VERSION/${REPOSITORY}_${VERSION}_x86_64-unknown-linux-musl.tar.xz"
        curl -sL -H 'Accept: application/octet-stream' -H 'Authorization: Bearer ${TOKEN}' ${ASSET_URL} > unknown-linux-musl.tar.gz
        tar -xf unknown-linux-musl.tar.gz
        rm -rf unknown-linux-musl.tar.gz
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        ORG: medical-software-quality
        REPOSITORY: documentation-as-code
        VERSION: ${{ github.action_ref }}
    - name: Check documentation
      shell: bash
      run: ./quality --path ${{ inputs.path }} > documentation.json
    - uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: ${{ inputs.artifact }}

